@startuml

class utilisateur {
  ID
  Pseudo 
  Age 
  PhotoDeProfil
  Statu
  ReseauSociaux
}

class serveur {
  ID
  Nom
  NombreMembre
}

class Role {
  isAdmin
  droits
}


utilisateur --> serveur
serveur .> Role : <<Extend>>


@enduml
