@startuml

class utilisateur {
  ID
  Pseudo 
  Age 
  PhotoDeProfil
  Statu
  ReseauSociaux
  adresseMail
  numTel
}

class serveur {
  ID
  Nom
  NombreMembre
  Alchannel 
}

class Role {
  isAdmin
  droits
}

class Channel {
  ID
  nom
}

class ChannelAudio{
  nbPersonne
}

class ChannelTextuel{
  Message
}

class Application {
 alServeur
}

utilisateur --> serveur
serveur .> Role : <<Extend>>
serveur --> Channel
Channel .> ChannelTextuel : <<Extend>>
Channel .> ChannelAudio : <<Extend>>

@enduml
