@startuml

actor enseignants
usecase Profil_Enseignants as PE
usecase Modifier_Profil_Enseignants as MPE
usecase Identiters as IE
usecase Module as ME
usecase Specialiter 
usecase consulter 

actor Secretariat
actor enseignantsVacataire as EV
actor Eleve 

usecase defini_le_module_de_ensegant as DME

enseignants -- MPE
Secretariat -- MPE 
Eleve -- consulter
consulter -- PE
MPE -- IE
MPE -- ME
EV -- MPE
MPE -- Specialiter
EV -- DME
Secretariat -- DME

@enduml
