@startuml

class Enseignant {
  idEnseignant
  nom
  prénom
  initiales 
  une photo
  un descriptif succinct
}

class formation{
  idFormation
  nom formation
}

class Module{
  idModule
  nom Module
  Initiales
}

class profil {
  idProfil
  Profil d un enseignant
}

class Eleve{

}

Enseignant "1" -- "1" formation : pratique 
Enseignant "1..*" -- "1..*" Module : assigner
Enseignant "1" -right- "1" profil : appartient
Eleve "1..*" -down- "1" profil : consulter

@enduml
