@startuml

autonumber
actor Enseignant
Enseignant -> systeme: connection

activate systeme
systeme -> profil: connection 

activate profil
profil -> profil: identification 
profil --> systeme: identificattion valider
systeme --> Enseignant: connecter

Enseignant -> systeme: modifier information
systeme -> profil: modification des information 
profil -> profil: sauvegarde modification
profil --> systeme: modification sauvegarder
systeme --> Enseignant: profil modifier avec succès



@enduml
